# Generated by Django 6.0.3 on 2026-04-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_creacion_tablas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DispositivoModel',
            new_name='DispositivosModel',
        ),
        migrations.RenameModel(
            old_name='GrupoModel',
            new_name='GruposModel',
        ),
    ]
