# Generated by Django 6.0.3 on 2026-04-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_creacion_de_vistas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariosmodel',
            old_name='is_staf',
            new_name='is_staff',
        ),
    ]
